version: "3.8"

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}

services:
  vpn:
    container_name: curbside-vpn
    image: fardjad/docker-network-exposer
    init: true
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./client-config:/etc/openvpn/client-config

  dns:
    container_name: devdns
    image: devdns-patched
    ports:
      - 5300:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NETWORK: ${DOCKER_NETWORK}
      DNS_DOMAIN: docker
